version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  migrations:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: migrations
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
    depends_on:
      - postgres
    networks:
      - app-network

  serverless:
    build: ./serverless
    ports:
      - "8000:8000"
    env_file:
      - ./serverless/.env
    volumes:
      - s3bucket:/mnt/s3bucket
    depends_on:
      - rabbitmq
      - filesystem

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

  filesystem:
    build: ./filesystem
    volumes:
      - s3bucket:/mnt/s3bucket
    env_file:
      - ./filesystem/.env
    privileged: true

volumes:
  postgres_data:
  s3bucket:

networks:
  app-network:
    driver: bridge
