services:
  app:
    hostname: app
    restart: always
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: build/Dockerfile.app
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  migrations:
    build:
      context: ./infra/database
      dockerfile: Dockerfile
    container_name: migrations
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/db
    depends_on:
      - postgres
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    build: ./infra/rabbitMQ
    ports:
      - "15672:15672"
    command: ["rabbitmq-server"]
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 2s
      retries: 20
    restart: always
    networks:
      - app-network
    entrypoint: /docker-entrypoint-initdb.d/init.sh

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
