// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Inteli-College/2024-2A-T02-EC11-G01/configs"
	"github.com/Inteli-College/2024-2A-T02-EC11-G01/internal/infra/repository"
	"github.com/Inteli-College/2024-2A-T02-EC11-G01/internal/infra/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeLocationsHandler() (*web.LocationHandler, error) {
	db, err := configs.SetupPostgres()
	if err != nil {
		return nil, err
	}
	locationRepository := repository.NewLocationRepository(db)
	locationHandler := web.NewLocationHandler(locationRepository)
	return locationHandler, nil
}

func InitializePredictionsHandler() (*web.PredictionHandler, error) {
	db, err := configs.SetupPostgres()
	if err != nil {
		return nil, err
	}
	predictionRepository := repository.NewPredictionRepository(db)
	predictionHandler := web.NewPredictionHandler(predictionRepository)
	return predictionHandler, nil
}

// wire.go:

var DBProviderSet = wire.NewSet(configs.SetupPostgres)

var LocationRepositorySet = wire.NewSet(DBProviderSet, repository.NewLocationRepository)

var PredictionRepositorySet = wire.NewSet(DBProviderSet, repository.NewPredictionRepository)
