FROM nvidia/cuda:12.6.1-cudnn-devel-ubuntu22.04

RUN apt-get update && apt-get upgrade -y && apt-get autoremove

# RUN  python3 -m pip3 install --upgrade pip3

# RUN pip install -r requirements.txt

# WORKDIR /code

# COPY . .

# CMD [ "python", "main.py" ]