name: Build and Push Docker Images to DockerHub

on:
  push:
    branches:
      - feat/github-workflow
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [app, prover, predictor, migrations, rabbitmq]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          case ${{ matrix.service }} in
            app)
              cd backend
              docker build -t carbonicos/app:latest -f ./build/Dockerfile.app .
              docker push carbonicos/app:latest
              ;;
            prover)
              cd backend
              docker build -t carbonicos/prover:latest -f ./build/Dockerfile.prover .
              docker push carbonicos/prover:latest
              ;;
            predictor)
              cd predictor
              docker build -t carbonicos/predictor:latest .
              docker push carbonicos/predictor:latest
              ;;
            migrations)
              cd infraestructure/database
              docker build -t carbonicos/migrations:latest .
              docker push carbonicos/migrations:latest
              ;;
            rabbitmq)
              cd infraestructure/rabbitmq
              docker build -t carbonicos/rabbitmq:latest .
              docker push carbonicos/rabbitmq:latest
              ;;
          esac
