name: Build and Push Docker Image to Dockerhub

on:
  push:
    branches:
      - feat/github-workflow
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: build/Dockerfile.app
          push: true
          tags: |
            carbonicos/app:latest

      - name: Build and push prover image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: build/Dockerfile.prover
          push: true
          tags: |
            carbonicos/prover:latest

      - name: Build and push predictor image
        uses: docker/build-push-action@v6
        with:
          context: ./predictor
          push: true
          tags: |
            carbonicos/predictor:latest

      - name: Build and push migrations image
        uses: docker/build-push-action@v6
        with:
          context: ./infraestructure/database
          push: true
          tags: |
            carbonicos/migrations:latest

      - name: Build and push rabbitmq image
        uses: docker/build-push-action@v6
        with:
          context: ./infraestructure/rabbitmq
          push: true
          tags: |
            carbonicos/rabbitmq:latest
