name: Build and Push Docker Image to ECR and update machine

on:
  push:
    branches:
      - feat/github-workflow
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo env file
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" 
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" 
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" 
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Compose images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Tag and Push Docker images to ECR
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URL=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/carbonicos
          
          docker-compose -f docker-compose.yml config | grep image | awk '{print $2}' | while read image_name; do
            image_base=$(basename $image_name)
            docker tag $image_name $REPOSITORY_URL:$IMAGE_TAG
            docker push $REPOSITORY_URL:$IMAGE_TAG
          done
